# Generated by Django 6.0.5 on 2026-06-02 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readinglistbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='readinglistbook',
            name='reading_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_books', to='books.readinglist'),
        ),
        migrations.AlterUniqueTogether(
            name='readinglistbook',
            unique_together={('reading_list', 'book'), ('reading_list', 'position')},
        ),
    ]
