# Generated by Django 6.0.5 on 2026-06-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover_image_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readinglistbook',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='readinglistbook',
            constraint=models.UniqueConstraint(fields=('reading_list', 'book'), name='unique_book_per_reading_list'),
        ),
        migrations.AddConstraint(
            model_name='readinglistbook',
            constraint=models.UniqueConstraint(fields=('reading_list', 'position'), name='unique_position_per_reading_list'),
        ),
    ]
