# Generated by Django 6.0.5 on 2026-06-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_readinglistbook_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinglist',
            options={'ordering': ['-created_at']},
        ),
    ]
